export const types = {
  TOGGLE_DRAWER: "TOGGLE_DRAWER",
  TOGGLE_DRAWER_SUCCEEDED: "TOGGLE_DRAWER_SUCCEEDED",
  TOGGLE_DIALOG: "TOGGLE_DIALOG",
  TOGGLE_DIALOG_SUCCEEDED: "TOGGLE_DIALOG_SUCCEEDED",
  LOAD_CANVAS_LIST: "LOAD_CANVAS_LIST",
  SAVE_CANVAS_INFO: "SAVE_CANVAS_INFO"
};
